	country=CN
	ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
	update_config=1
	 
	
	
	

	
	
	
	
	
	network={
		ssid="ExampleSSID1"
		psk="example_password"
		priority=2
	}
	network={
		ssid="ExampleSSID2"
		psk="example_password"
	}
	network={
		ssid="ExampleSSID3"
		psk="123456"
		priority=3
	}
	network={
		ssid="ACL"
		psk="123456"
		priority=4
	}